reviewers:
  defaults:
    - repository-owners

  groups:
    repository-owners:
      - mholubinka1

files:
  '**':
    - repository-owners

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: false

