repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.10
    hooks:
      - id: uv-lock
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.3.1
    hooks:
      - id: mypy
        additional_dependencies: [
          'types-requests',
          'types-simplejson',
          'types-PyYAML',
          'types-pytz',
          'sqlalchemy-stubs',
        ]
  - repo: https://github.com/pycqa/isort
    rev: 9.0.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.6
    hooks:
      - id: ruff
        args: [ --fix ]
