services:
  bromley-bin-reminder:
    container_name: bin-reminder
    image: mholubinka1/bromley-bin-reminder:latest
    pull_policy: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - /mnt/media/pi-media/containers/bin-reminder/config:/config
    restart: unless-stopped

#docker-compose up --pull=always -d
